using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace FluentFlyout.SourceGenerators
{
    [Generator]
    public class SearchItemsGenerator : ISourceGenerator
    {
        public void Initialize(GeneratorInitializationContext context) { }

        public void Execute(GeneratorExecutionContext context)
        {
            var searchItems = new List<(string pageType, string resourceKey, string elementId)>();
            var isWinUi = context.ParseOptions is CSharpParseOptions csharpParseOptions
                && csharpParseOptions.PreprocessorSymbolNames.Contains("FLUENTFLYOUT_WINUI");

            foreach (var file in context.AdditionalFiles.Where(f => f.Path.EndsWith(".xaml", StringComparison.OrdinalIgnoreCase) && f.Path.Replace('\\', '/').IndexOf("/Pages/", StringComparison.OrdinalIgnoreCase) >= 0))
            {
                var pageName = Path.GetFileNameWithoutExtension(file.Path);

                try
                {
                    var text = file.GetText(context.CancellationToken)?.ToString();
                    if (string.IsNullOrWhiteSpace(text)) continue;

                    var doc = XDocument.Parse(text);
                    foreach (var element in doc.Descendants())
                    {
                        var tagAttr = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "Tag");
                        if (tagAttr != null && tagAttr.Value == "Indexable")
                        {
                            // WinUI uses SearchIndex.ResourceKey or x:Uid. Keep DynamicResource
                            // parsing for the WPF branch while both implementations coexist.
                            var textBlocks = element.Descendants().Where(e => e.Name.LocalName == "TextBlock");
                            string? resourceKey = null;
                            var explicitResource = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "ResourceKey");
                            var uid = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "Uid");
                            resourceKey = explicitResource?.Value ?? uid?.Value;
                            foreach (var tb in textBlocks)
                            {
                                if (resourceKey != null) break;
                                var textAttr = tb.Attributes().FirstOrDefault(a => a.Name.LocalName == "Text");
                                if (textAttr != null && textAttr.Value.StartsWith("{DynamicResource ") && textAttr.Value.EndsWith("}"))
                                {
                                    resourceKey = textAttr.Value.Substring("{DynamicResource ".Length, textAttr.Value.Length - "{DynamicResource ".Length - 1).Trim();
                                    break;
                                }
                            }

                            // If no TextBlock, maybe the element itself has a Text property
                            if (resourceKey == null)
                            {
                                var textAttr = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "Text");
                                if (textAttr != null && textAttr.Value.StartsWith("{DynamicResource ") && textAttr.Value.EndsWith("}"))
                                {
                                    resourceKey = textAttr.Value.Substring("{DynamicResource ".Length, textAttr.Value.Length - "{DynamicResource ".Length - 1).Trim();
                                }
                            }
                            // Also check content or header... let's keep it simple for now and see if TextBlocks are enough.

                            var nameAttr = element.Attributes().FirstOrDefault(a => a.Name.LocalName == "Name");

                            if (nameAttr != null && resourceKey != null)
                            {
                                searchItems.Add((pageName, resourceKey, nameAttr.Value));
                            }
                        }
                    }
                }
                catch (Exception)
                {
                    // Ignore parsing errors
                }
            }

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("namespace FluentFlyoutWPF");
            sb.AppendLine("{");
            sb.AppendLine("    public partial class SettingsWindow");
            sb.AppendLine("    {");
            sb.AppendLine("        public static readonly (Type TargetPageType, string ResourceKey, string TargetElementId)[] SearchItems = new (Type, string, string)[]");
            sb.AppendLine("        {");

            foreach (var item in searchItems)
            {
                sb.AppendLine($"            (typeof(Pages.{item.pageType}), \"{item.resourceKey}\", \"{item.elementId}\"),");
            }

            sb.AppendLine("        };");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            if (isWinUi)
            {
                sb.AppendLine();
                sb.AppendLine("namespace FluentFlyout.App");
                sb.AppendLine("{");
                sb.AppendLine("    public static class GeneratedSearchIndex");
                sb.AppendLine("    {");
                sb.AppendLine("        public static readonly global::FluentFlyout.Core.SearchIndexEntry[] SearchItems = new global::FluentFlyout.Core.SearchIndexEntry[]");
                sb.AppendLine("        {");
                foreach (var item in searchItems)
                {
                    var escapedKey = item.resourceKey.Replace("\\", "\\\\").Replace("\"", "\\\"");
                    var escapedId = item.elementId.Replace("\\", "\\\\").Replace("\"", "\\\"");
                    sb.AppendLine($"            new(\"{escapedId}\", \"{escapedKey}\", new[] {{ \"{escapedKey}\" }}),");
                }
                sb.AppendLine("        };");
                sb.AppendLine("    }");
                sb.AppendLine("}");
            }

            context.AddSource("SearchItems.g.cs", sb.ToString());
        }
    }
}
